module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    fontFamily: {
      smpx: ['Small Pixel7'],
      outpxd: ['Outline Pixel7 Solid'],
    },
    extend: {
      colors: {
        primary: {
          100: '#e0c39f',
          200: '#d3aa78',
          300: '#c79252',
          400: '#c58f4d',
          500: '#CE8D3E',
          600: '#9a6b32',
          700: '#875e2c',
          800: '#745025',
          900: '#60431f',
        },
        gray: {
          100: '#f7fafc',
          200: '#edf2f7',
          300: '#e2e8f0',
          400: '#cbd5e0',
          500: '#a0aec0',
          600: '#718096',
          700: '#4a5568',
          800: '#2d3748',
          900: '#1a202c',
        },
      },
      lineHeight: {
        hero: '4.5rem',
      },
      backgroundImage: {
        hero: "url('/assets/images/background.png')",
        mobile: "url('/assets/images/mobile_background.png')",
        acquire_desktop: "url('/assets/images/background_acquire_desktop.png')",
        acquire_mobile: "url('/assets/images/background_acquire_mobile.png')",
        togglebutton: "url('/assets/images/togglebutton.png')",
        memo: "url('/assets/images/memo.png')",
        roadmap: "url('/assets/images/roadmap.png')",
        d_hiw_1: "url('/assets/images/d_hiw_1.png')",
        d_hiw_2: "url('/assets/images/d_hiw_2.png')",
        d_hiw_3: "url('/assets/images/d_hiw_3.png')",
        d_hiw_4: "url('/assets/images/d_hiw_4.png')",
        d_hiw_5: "url('/assets/images/d_hiw_5.png')",
        m_hiw_1: "url('/assets/images/m_hiw_1.png')",
        m_hiw_2: "url('/assets/images/m_hiw_2.png')",
        m_hiw_3: "url('/assets/images/m_hiw_3.png')",
        m_hiw_4: "url('/assets/images/m_hiw_4.png')",
        fifthhowitworks: "url('/assets/images/fifthhowitworks.png')",
        tokenomics_1: "url('/assets/images/tokenomics_1.png')",
        tokenomics_2: "url('/assets/images/tokenomics_2.png')",
        tokenomics_3: "url('/assets/images/tokenomics_3.png')",
        tokenomics_4: "url('/assets/images/tokenomics_4.png')",
        tokenomics_description: "url('/assets/images/tokenomics_description.png')",
        presaleendtime: "url('/assets/images/presaleendtime.png')",
        availableamount: "url('/assets/images/availableamount.png')",
        connectwallet: "url('/assets/images/connectwallet.png')",
        input1: "url('/assets/images/input1.png')",
        becomeanearlyinvestor: "url('/assets/images/becomeanearlyinvestor.png')",
        thestabletoken_horizontal: "url('/assets/images/thestabletoken_horizontal.png')",
        thestabletoken_vertical: "url('/assets/images/thestabletoken_vertical.png')",
        rightarrow_yellow: "url('/assets/images/rightarrow_yellow.png')",
        rightarrow_brown: "url('/assets/images/rightarrow_brown.png')",
        suppliedliquidity: "url('/assets/images/suppliedliquidity.png')",
        acquirecard: "url('/assets/images/acquirecard.png')",
        roadmap_horizontal: "url('/assets/images/roadmap_horizontal.png')",
        roadmap_vertical: "url('/assets/images/roadmap_vertical.png')",
        privatesaleinfo: "url('/assets/images/privatesaleinfo.png')",
        acquireamount: "url('/assets/images/acquireamount.png')",
        coinselect: "url('/assets/images/coinselect.png')",
      },
    },
    screens: {
      tablet1: '900px',
      laptop: '960px',
      desktop: '1100px',
    },
  },
  variants: {
    extend: {
      fontFamily: ['hover', 'focus'],
    },
  },
  plugins: [],
  corePlugins: {
    fontFamily: true,
    translate: true,
    transform: true,
    stroke: true,
  },
};
